# Generated by Django 3.2 on 2021-05-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
