# Generated by Django 3.2 on 2021-05-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_order_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_email',
            new_name='user_id',
        ),
    ]
